### ISSUE TITLE
Create Test Plan

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#157] opened 2022-06-28 16:08 UTC
Refer to old issue to get started https://github.com/MetaCell/open-physiology-viewer/issues/121

- Use master branch https://github.com/MetaCell/open-physiology-viewer
- Existing tests for reference https://github.com/MetaCell/open-physiology-viewer/tree/master/test
- Documentation http://open-physiology-viewer-docs.surge.sh/

**Comment by SimaoBolota-MetaCell** [comment] 2022-07-15 10:45
**Test Plan** is being created as an AirTable:
- https://airtable.com/appXiARM4nNqpVERG/tblO23T8pAS3aB9Pn/viw5kGwAF0LqMOPqK?blocks=hide

**Comment by SimaoBolota-MetaCell** [comment] 2022-07-21 17:19
@jrmartin 

**Test Cases can be found here:**
https://airtable.com/appXiARM4nNqpVERG/tblO23T8pAS3aB9Pn/viw5kGwAF0LqMOPqK?blocks=hide 

The more specific layout related test cases will be added onto the same AirTable in the next days.

Some Notes
---
**Test Cases** are divided into

- E2E
 - Functional - main application functional tests completed (some layout specific tests are being added)
 - Smoke - waiting for review of the functional tests to then define what's more important
- Integration - some basic test cases for now

<img width="346" alt="Screenshot at Jul 21 12-35-38" src="https://user-images.githubusercontent.com/99416933/180274294-69acf45a-2740-42be-b115-ee763f86a4a2.png">


----

**Notes on Test Cases**

- Every test case is grouped into its testing type and level. Additionally test cases are grouped by SubSection, which represents a specific group of functionalities from the application.
- Applying the 'Implemented' filter allows you to see test cases for working functionalities.
<img width="1401" alt="Screenshot at Jul 21 12-26-50" src="https://user-images.githubusercontent.com/99416933/180274339-18f7585c-b0db-4760-9229-2e9a77eb096c.png">

- The most important fields are:
 - Code - unique identifier to the specific test case
 - Pre-Step - the test case can only be executed if the test case listed in the Pre-Step has successfully passed
 - Actions - What to perform in the application to get the wanted results
 - Verification - What to expect and verify by performing the Action
 - Outcome Screenshot - an application screenshot helping to identify the functionality and what it is intended to do
 - Pass - Field specific for each release, where the test cases are marked as passed successfully (checked)  or not (unchecked)
 - Error Description - Field specific for each release. In case the test case fails, it needs to be documented
 - Error attachment - Field specific for each release. In case the test case fails, it needs to be documented
 - GitHub Issue - Since an issue was identified, it needs to be created on the projects GitHub page. This field is a URL field to the GitHub created issue

----

The intent behind the **Functional Test Cases** is to:

- check if every UI element works and is labelled as intended
- check if specific chore elements are being displayed with the shape and format of the documentation
- test different models and how they are displayed

**Comment by SimaoBolota-MetaCell** [comment] 2022-07-27 10:28
fyi @jrmartin 

Additional Test Cases, specific for the Open Physiology Viewer Components
---

**Base Model: Elements Connections - Test Cases**


- Tests are divided into the different groups (F, D and N) for anchors, wires and regions
- In each test case, the purpose is to toggle only a specific group anchor, wire and region. From left to right (clockwise) check the elements names, id's and connections
- The verification step contains the anchor, wire or region ID's and names
- If a change to the groups elements is made, the id's and names need to be updated
<img width="1437" alt="Screenshot at Jul 27 11-26-25" src="https://user-images.githubusercontent.com/99416933/181225402-d8234841-5472-450a-9e1c-0856c5924c68.png">


**Connectivity Model: Elements Connections - Test Cases**


- This set of test cases differs from the Base Model one's
- First, the ```dev-layout-conn.json model```is merged with the base model
- The necessary groups and dynamic groups are then toggled individually. The main objective is to then compare the elements displayed in the Open Physiology viewer with the screenshots attached in the 'Outcome Screenshot' section. The elements must match
- Since there are a lot of groups to toggle, if a change to the groups or dynamic groups elements is made, only the screenshots need to be updated for this case

<img width="1440" alt="Screenshot at Jul 27 11-26-00" src="https://user-images.githubusercontent.com/99416933/181225474-6381d36e-9fe0-4158-b525-300b57b2ee2d.png">

**Closed** 2022-10-04 16:10 UTC
