### ISSUE TITLE
Enable Neurulated Neuron

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#166] opened 2022-07-29 08:03 UTC
Following specifications defined here https://docs.google.com/document/d/1X_v5Zjf9iQnaAhrIEQBd5odi4TE6DxO2E06CUqcI3wI/edit and further expanded in the agenda .

We need to create the functionality to toggle on and off Neurulated groups. 
- If a neurulated group is turned on, everything not related to the Neuron will be turned off. Meaning all scaffold map where the Neuron is not anchored or hosted by. Only the edges, nodes and housing Lyphs of the toggle neuron will be visible.

**Comment by ddelpiano** [comment] 2022-10-04 16:20
duplicate of #180

**Closed by ddelpiano** 2022-10-04 16:20 UTC
